name: phone_plus
description: A flutter plugin for accessing phone state in Android and iOS.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.morabaa.phone_plus
        pluginClass: PhonePlusPlugin
      ios:
        pluginClass: PhonePlusPlugin
